version: "2"
services:
  ical4notion:
      # image: "node:latest"
      image: "node:18-alpine3.17"
      environment:
        - NOTION_TOKEN=${NOTION_TOKEN}
      volumes:
        - .:/app
      ports:
        - "80"
      working_dir: /app
      command: sh -c "npm install && npm start"
